'use client';

import React from 'react';
import Link from 'next/link';
import { LegalLayout } from '@/components/LegalLayout';
import { ShieldCheck, Scale, FileCheck, CheckCircle2 } from 'lucide-react';

export default function TermsOfServicePage() {
  return (
    <LegalLayout
      title="Terms of Platform Service"
      subtitle="Standard corporate terms governing usage of the JurisDraft software platform, automated drafting studios, and cloud vaults."
      lastUpdated="September 10, 2026"
      version="Version 1.2"
    >
      <div className="space-y-8 text-slate-700 text-xs sm:text-sm leading-relaxed">
        
        {/* Notice Callout */}
        <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg flex items-start gap-3">
          <ShieldCheck className="w-5 h-5 text-slate-700 flex-shrink-0 mt-0.5" />
          <div className="text-xs space-y-1">
            <span className="font-bold text-slate-900">Binding Enterprise Agreement:</span>
            <p className="text-slate-600">
              By accessing, browsing, or utilizing the JurisDraft platform, creating an account, or downloading any compiled documentation, you agree to be bound by these Terms of Service. If you are entering into these Terms on behalf of an enterprise entity, you represent that you possess the requisite authority to bind that entity.
            </p>
          </div>
        </div>

        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 font-serif border-b border-slate-200 pb-1.5 flex items-center gap-2">
            <span className="text-[#D4AF37]">1.</span> Nature of the Software &amp; Non-Legal Representation
          </h2>
          <p>
            JurisDraft provides autonomous legal document automation software, standard template interpolation, and secure cloud repositories. <strong>JurisDraft is a software technology vendor and is not a law firm, licensed legal practitioner, or legal referral service.</strong>
          </p>
          <p>
            The platform, including its AI intake assistants, interactive clause editors, and pre-compiled templates, does not provide legal representation, statutory analysis, or formal attorney-client counsel. Using JurisDraft does not establish an attorney-client relationship or create any attorney-client evidentiary privilege.
          </p>
          <p className="p-3 bg-amber-50/60 border border-amber-200 rounded-md text-amber-900 text-xs">
            <strong>Mandatory Review Requirement:</strong> All agreements compiled through JurisDraft are preliminary drafts. Users must have each document independently reviewed, adapted, and certified by qualified legal counsel licensed in the applicable governing jurisdiction prior to execution.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 font-serif border-b border-slate-200 pb-1.5 flex items-center gap-2">
            <span className="text-[#D4AF37]">2.</span> Customer Data Ownership &amp; Intellectual Property
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 my-2">
            <div className="p-3.5 rounded-lg border border-emerald-200 bg-emerald-50/40 space-y-1">
              <div className="font-bold text-emerald-950 text-xs flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                100% Customer Owned
              </div>
              <p className="text-slate-600 text-xs">
                You retain complete, unencumbered ownership of all data, corporate parameters, and customized contract text entered into or generated by the platform.
              </p>
            </div>
            <div className="p-3.5 rounded-lg border border-slate-200 bg-slate-50 space-y-1">
              <div className="font-bold text-slate-900 text-xs flex items-center gap-1.5">
                <Scale className="w-4 h-4 text-slate-700" />
                Common Paper Standards
              </div>
              <p className="text-slate-600 text-xs">
                Base document templates are derived from open-standard frameworks licensed under Creative Commons Attribution 4.0 International (CC BY 4.0).
              </p>
            </div>
          </div>
          <p>
            JurisDraft claims no copyright, trade secret, or ownership rights over your completed agreements, counterparty names, disclosure terms, or execution artifacts.
          </p>
        </section>

        {/* Section 3 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 font-serif border-b border-slate-200 pb-1.5 flex items-center gap-2">
            <span className="text-[#D4AF37]">3.</span> User Accounts &amp; Corporate Vault Security
          </h2>
          <p>
            To save drafts, synchronize documents across teams, or access encrypted cloud repositories, users must register for a verified JurisDraft account. You are solely responsible for safeguarding your authentication credentials and for all activities conducted under your vault.
          </p>
          <p>
            You agree to immediately notify JurisDraft at <code className="text-xs bg-slate-100 px-1.5 py-0.5 rounded text-slate-800">security@jurisdraft.io</code> upon discovering any unauthorized vault access or security compromise.
          </p>
        </section>

        {/* Section 4 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 font-serif border-b border-slate-200 pb-1.5 flex items-center gap-2">
            <span className="text-[#D4AF37]">4.</span> Prohibited Uses
          </h2>
          <p>You agree not to use the JurisDraft platform to:</p>
          <ul className="list-disc list-inside space-y-1 text-slate-600 pl-2 text-xs sm:text-sm">
            <li>Generate fraudulent, deceptive, or statutorily unlawful legal agreements;</li>
            <li>Misrepresent automated drafts as having been prepared by a licensed attorney when no such attorney has reviewed them;</li>
            <li>Interfere with, compromise, or probe the infrastructure, rate limiters, or authentication mechanisms of the platform;</li>
            <li>Reverse-engineer or systematically scrape template schemas or backend endpoints without written consent.</li>
          </ul>
        </section>

        {/* Section 5 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 font-serif border-b border-slate-200 pb-1.5 flex items-center gap-2">
            <span className="text-[#D4AF37]">5.</span> Warranty Disclaimer &amp; Limitation of Liability
          </h2>
          <p className="uppercase text-xs font-bold text-slate-900 tracking-wider">
            Disclaimer of Statutory Warranties
          </p>
          <p className="text-slate-600 text-xs leading-relaxed">
            THE PLATFORM, INCLUDING ALL TEMPLATES, CONVERSATIONAL INTAKE ASSISTANTS, AND EXPORTED COMPILATIONS, IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, OR NON-INFRINGEMENT. JURISDRAFT DOES NOT WARRANT THAT GENERATED CONTRACTS WILL SATISFY YOUR SPECIFIC LEGAL REQUIREMENTS OR WITHSTAND STATUTORY CHALLENGE IN ANY COURT.
          </p>
          <p className="uppercase text-xs font-bold text-slate-900 tracking-wider pt-2">
            Cap on Aggregate Liability
          </p>
          <p className="text-slate-600 text-xs leading-relaxed">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL JURISDRAFT, ITS AFFILIATES, OFFICERS, OR AGENTS BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, EXEMPLARY, OR SPECIAL DAMAGES (INCLUDING LOSS OF BUSINESS PROFITS, CONTRACT DAMAGES, OR LITIGATION COSTS) ARISING OUT OF OR IN CONNECTION WITH THE USE OR INABILITY TO USE THE PLATFORM. IN ALL CASES, JURISDRAFT&apos;S AGGREGATE LIABILITY SHALL BE STRICTLY LIMITED TO THE AMOUNT PAID BY YOU TO JURISDRAFT IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR ONE HUNDRED UNITED STATES DOLLARS ($100.00 USD), WHICHEVER IS GREATER.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3">
          <h2 className="text-base sm:text-lg font-bold text-slate-900 font-serif border-b border-slate-200 pb-1.5 flex items-center gap-2">
            <span className="text-[#D4AF37]">6.</span> Governing Law &amp; Dispute Resolution
          </h2>
          <p>
            These Terms shall be governed by and construed in accordance with the substantive laws of the <strong>State of Delaware, United States</strong>, without giving effect to conflicts of law principles.
          </p>
          <p>
            Any dispute, controversy, or claim arising under or relating to these Terms or the platform shall be settled by binding confidential arbitration administered by the American Arbitration Association (AAA) in Wilmington, Delaware, in accordance with its Commercial Arbitration Rules.
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-3 pt-4 border-t border-slate-200">
          <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
            7. Contact &amp; Corporate Inquiries
          </h2>
          <p className="text-xs text-slate-500">
            JurisDraft Platform Legal Team • <a href="mailto:legal@jurisdraft.io" className="text-slate-900 underline font-semibold">legal@jurisdraft.io</a> • 1201 North Market Street, Suite 1800, Wilmington, DE 19801.
          </p>
        </section>

      </div>
    </LegalLayout>
  );
}
